export const FETCH_GLOATS_REQUEST = 'FETCH_GLOATS_REQUEST';
export const FETCH_GLOATS_SUCCESS = 'FETCH_GLOATS_SUCCESS';

export const CREATE_API_TOKEN_REQUEST = 'CREATE_API_TOKEN_REQUEST';
export const CREATE_API_TOKEN_SUCCESS = 'CREATE_API_TOKEN_SUCCESS';
