export const CLICK_ADMIRE = 'CLICK_ADMIRE';
export const CLICK_NEW_GLOAT = 'CLICK_NEW_GLOAT';
export const CLOSE_NEW_GLOAT = 'CLOSE_NEW_GLOAT';

export const OPEN_USER_MENU = 'OPEN_USER_MENU';
export const CLOSE_USER_MENU = 'CLOSE_USER_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';

export const CREATE_ADMIRE_REQUEST = 'CREATE_ADMIRE_REQUEST';
export const CREATE_ADMIRE_SUCCESS = 'CREATE_ADMIRE_SUCCESS';

export const DELETE_ADMIRE_REQUEST = 'DELETE_ADMIRE_REQUEST';
export const DELETE_ADMIRE_SUCCESS = 'DELETE_ADMIRE_SUCCESS';

export const FETCH_GLOATS_REQUEST = 'FETCH_GLOATS_REQUEST';
export const FETCH_GLOATS_SUCCESS = 'FETCH_GLOATS_SUCCESS';

export const CREATE_GLOAT_REQUEST = 'CREATE_GLOAT_REQUEST';
export const CREATE_GLOAT_SUCCESS = 'CREATE_GLOAT_SUCCESS';

export const CREATE_API_TOKEN_REQUEST = 'CREATE_API_TOKEN_REQUEST';
export const CREATE_API_TOKEN_SUCCESS = 'CREATE_API_TOKEN_SUCCESS';
export const CREATE_API_TOKEN_FAILURE = 'CREATE_API_TOKEN_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
