export const FETCH_GLOATS_REQUEST = 'FETCH_GLOATS_REQUEST';
export const FETCH_GLOATS_SUCCESS = 'FETCH_GLOATS_SUCCESS';

export const CREATE_GLOAT_REQUEST = 'CREATE_GLOAT_REQUEST';
export const CREATE_GLOAT_SUCCESS = 'CREATE_GLOAT_SUCCESS';

export const CREATE_API_TOKEN_REQUEST = 'CREATE_API_TOKEN_REQUEST';
export const CREATE_API_TOKEN_SUCCESS = 'CREATE_API_TOKEN_SUCCESS';
export const CREATE_API_TOKEN_FAILURE = 'CREATE_API_TOKEN_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const OPEN_USER_MENU = 'OPEN_USER_MENU';
export const CLOSE_USER_MENU = 'CLOSE_USER_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
