const exampleGloats = [
  'Most people fear the Reaper. I consider him a promising rookie.',
  'When I play Monopoly, it affects the actual world economy.',
  'I will never have a heart attack. My heart isn\'t nearly foolish enough to attack me.',
  'I once ate an entire bottle of sleeping pills. They made me blink.',
  'I don\'t chew gum. I chew tin foil.',
  'My brain waves are suspected to be harmful to cell phones.',
  'When you\'re me, anything + anything is equal to 1. One roundhouse kick to the face.',
  'I killed two stones with one bird.',
  'If I want your opinion, I\'ll beat it into you.',
  'I can dereference NULL.',
  'I had to register every part of my body as a separate lethal weapon.',
  'I keep my friends close and my enemies closer. Close enough to drop them with one round house kick to the face.',
  'I once participated in the running of the bulls. I walked.',
  'I can install a 64 bit OS on a 32 bit machine.',
  'The quickest way to a man\'s heart is with my fist.',
  'I once ordered a steak in a restaurant. The steak did what it was told.',
  'I crossed the road. No one has ever dared question my motives.',
  'I can write to an output stream.',
  'Tough men eat nails for breakfast. But I do all of my grocery shopping at Home Depot.',
  'I use a night light. Not because I am afraid of the dark, but because the dark is afraid of me.',
  'I can instantiate an abstract class.',
  'I type with one finger. I point it at the keyboard and the keyboard does the rest.',
  'I can speak Braille.',
  'I always know the EXACT location of Carmen San Diego.',
  'We live in a constantly expanding universe. All of it is trying to get away from me.',
  'I can touch MC Hammer.',
  'There is no such thing as global warming. I was cold, so I turned the sun up.',
  'I can judge a book by its cover.',
  'I walked into a bar. The bar said "ouch."',
  'I once fought Superman. The loser had to wear his underwear over his pants.',
  'D-Day was my Eagle Scout project.',
  'I have inside jokes with complete strangers.',
  'When life gives me lemons, I return them for a refund.',
  'I was bitten by a cobra. After five days of excruciating pain, the cobra died.',
  'I don\'t dial the wrong number. You answer the wrong phone.',
  'I can delete the recycling bin.',
  'I do not sleep. I wait.',
  'When I work out, I don\'t get stronger. The machine does.',
  'When I turned 18, my parents moved out.',
  'When I swim in the ocean, the sharks are in steel cages.',
  'I wear sunglasses so my eyes won\'t hurt the sun.',
];

const getExampleGloat = () => exampleGloats[Math.floor(Math.random() * exampleGloats.length)];

export default getExampleGloat;
